# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
sudo: required
language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      libicu-dev
      libfreetype6-dev
      ant
      r-cran-chron
      r-cran-zoo
      r-cran-shiny
      r-cran-ggplot2
      r-cran-gdata
      r-cran-gridbase
      r-cran-gridextra
      r-cran-mgcv
      r-cran-spatstat
      r-cran-reshape2
      r-cran-rcurl
      r-cran-plyr
      r-cran-roxygen2

r_packages:
  - akima
  - chron
  - dplR
  - dplyr
  - Ecdat
  - Ecfun
  - extrafont
  - gdata
  - ggplot2
  - gplots
  - grid
  - gridExtra
  - gWidgets
  - mgcv
  - mosaic
  - plyr
  - RCurl
  - reshape2
  - shiny
  - spatstat
  - sysfonts
  - xkcd
  - zoo
  - roxygen2

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - Rscript prepare.r
  - ./test.sh

notifications:
  slack: endtoendprovenance:DNYqXZWhV1c3eRhkjGYyjCEv
